title: My Blog
description: My Personal Blog
author: Ko Min Than Htut
logo: https://scontent.frgn1-1.fna.fbcdn.net/v/t1.0-1/p160x160/64494741_113009163294462_6826808160024526848_n.jpg?_nc_cat=109&_nc_oc=AQkVIau4j8olekuLtkSl7qoMxMCOthpXk7fLNGvYbKqt2rSX4jYfA_qiRRgrXGpIqI4&_nc_ht=scontent.frgn1-1.fna&oh=b43779f5f66ed0232a1de100f64a179d&oe=5DE2CF7B
github: https://github.com/kominthanhtut
about: Freelance developer

baseurl: "https://kominthanhtut.github.io"
url: "https://kominthanhtut.github.io"

allowsearch: true

disqus_shortname: aboutashu
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
